version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: vms_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: vms_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vms_db
      MYSQL_USER: vms_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    image: nginx:latest
    container_name: vms_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
