controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#app_install:
#    path: /install/{step}
#    controller: App\Controller\InstallController::install
##    condition: "file('/var/www/installed')"
#    condition: "true"
