controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#    type: annotation
#    prefix: /{_locale}
#    requirements:
#        _locale: en|de

# TODO: FIX TRANSLATION STUFF / ROUTE / Annotation

#app_install:
#    path: /install/{step}
#    controller: App\Controller\InstallController::install
##    condition: "file('/var/www/installed')"
#    condition: "true"
